### ISSUE TITLE
Demoexample 'User couldn't be logged on'

### ISSUE THREAD

**Issue by PatrickFrasheri** [hesstobi/mosaik-powerfactory#1]
How to provide login data? Your code example doesn't work as I get the above mentioned error message
and I cannot read the documentation because I am 
'unable to access 'https://gitlab.evieeh.local/tobias.hess/mosaik-powerfactory.git/': Could not resolve host: gitlab.evieeh.local'

**Comment by hesstobi** [comment]
Please use the repro on github
https://github.com/hesstobi/mosaik-powerfactory.git

**Comment by PatrickFrasheri** [comment]
Yeah I wanted to, but I cannot put sphinx on my PATH which is needed for the 'make html' command, because I'm at work and do not have administrator rights.
Could you tell me how to provide login data to connect to powerfactory in your example code? It doesn't work without it
